language: node_js

node_js:
  - "8"
  - "10"
  - "12"

jobs:
  include:
    - stage: release
      node_js: "8"
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: master
        script: npm run release
